package com.qrazy.bean;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class FixedMsgBean {

	public String SITE_NAME;
	public String STEP_TYPE;
	public String STEP_DATA;
	public String STEP_STYLE;
	public String STEP_DONE;
	public String TITLE_CUSTOMIZE;
	public String LABEL_IMG_TYPE;
	public String LABEL_IMG_SIZE;
	public String LABEL_COLOR;
	public String LABEL_BG;
	public String LABEL_FINDER;
	public String LABEL_PIXEL;
	public String LABEL_LOGO;
	public String LABEL_WITH_LOGO;
	public String LABEL_WITHOUT_LOGO;
	public String LABEL_BIG;
	public String LABEL_SMALL;
	public String LABEL_PROFILE;
	public String LABEL_SCAN;
	public String LABEL_CREATE;
	public String LABEL_UPDATE;
	public String LABEL_LOGO_SIZE;
	public String LABEL_NAME;
	public String LABEL_DATA;
	public String LABEL_ID;
	public String LABEL_PASSWORD;
	public String LABEL_CONFIRM;
	public String LABEL_EMAIL;
	public String LABEL_PROFILE_IMG;
	public String LABEL_STATIC;
	public String LABEL_DYNAMIC;
	public String LABEL_EXISTENCE;
	public String BTN_GENERATE;
	public String BTN_RESET;
	public String BTN_DOWNLOAD;
	public String BTN_SAVE;
	public String BTN_SHOW;
	public String BTN_CUSTOMIZE;
	public String BTN_UPDATE;
	public String BTN_SELECT_FILE;
	public String LINK_DETAIL;
	public String TITLE_LEARN;
	public String TITLE_SOLUTION;
	public String TITLE_PRODUCT;
	public String TITLE_SOLUTION_PROBLEM;
	public String TITLE_SOLUTION_SOLUTION;
	public String TITLE_PRODUCT_SUMMARY;
	public String TITLE_PRODUCT_DETAIL;
	public String TITLE_DASHBOARD;
	public String TITLE_STATIC_DYNAMIC_DESCRIPTION;
	public String TITLE_QR_CODE_SHOW;
	public String TITLE_NUMBER;
	public String TITLE_LOGIN;
	public String TITLE_BACK;
	public String TITLE_DETAIL;
	public String DEVELOPING;
	public String PREPARING;
	public String SERVICE_RELEASED_DATE;
	public String LABEL_QR_GENERATE_TYPE;
	public String DESCRIPTION_WEB;
	public String DESCRIPTION_DEFAULT;
	public String DESCRIPTION_TEXT;
	public String DESCRIPTION_WIFI;
	public String DESCRIPTION_BULK;
	public String DESCRIPTION_FILE;
	public String DESCRIPTION_GENERATE_TYPE_DYNAMIC;
	public String DESCRIPTION_GENERATE_TYPE_STATIC;
	public String DESCRIPTION_GENERATE_TYPE_DYNAMIC_ONLY;
	public String DESCRIPTION_STATIC;
	public String DESCRIPTION_STATIC_DETAIL;
	public String DESCRIPTION_DYNAMIC;
	public String DESCRIPTION_DYNAMIC_DETAIL;
	public String DESCRIPTION_DYNAMIC_ONLY;
	public String DESCRIPTION_DYNAMIC_ONLY_DETAIL;
	public String ABOUT_STATIC_DYNAMIC;
	public String BTN_DASHBOARD;
	public String BTN_LOGIN;
	public String BTN_LOGOUT;
	public String BTN_CHANGE;
	public String BTN_LANG;
	public String BTN_DETAIL;
	public String BTN_DELETE;
	public String NAV_STYLE_BASIC;
	public String NAV_STYLE_PIXEL;
	public String NAV_STYLE_FINDER;
	public String NAV_STYLE_TEMPLATE;
	public String NAV_STYLE_FRAME;
	public String HERO_MSG;
}
