spring.application.name=qrazy
server.servlet.context-path=/qrazy
server.port=8080
spring.thymeleaf.encoding=UTF-8
#spring.messages.basename=messages/messages 
spring.messages.fallback-to-system-locale=false
spring.messages.cache-duration=3600
spring.thymeleaf.check-template-location=false
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/qrazy}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- JPA / Hibernate ---
spring.sql.init.mode=always
spring.sql.init.platform=postgresql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
image_folder_path_qr_code=./src/main/resources/static/images/qrcodes/
image_folder_path_appication_customize=./src/main/resources/static/images/common/customize/
image_folder_path_appication_customize_logo=./src/main/resources/static/images/common/customize/logo/
image_folder_path_appication_common=./src/main/resources/static/images/common/